// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function ListConnections():Promise<types.JSResp>;

export function SaveConnection(arg1:types.Connection):Promise<types.JSResp>;

export function Startup(arg1:context.Context):Promise<void>;
