// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListConnections() {
  return window['go']['services']['connectionService']['ListConnections']();
}

export function SaveConnection(arg1) {
  return window['go']['services']['connectionService']['SaveConnection'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['connectionService']['Startup'](arg1);
}
