// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Startup(arg1) {
  return window['go']['services']['mysqlService']['Startup'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['services']['mysqlService']['TestConnection'](arg1);
}
