// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListDatabases(arg1) {
  return window['go']['services']['mysqlService']['ListDatabases'](arg1);
}

export function ListTables(arg1) {
  return window['go']['services']['mysqlService']['ListTables'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['mysqlService']['Startup'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['services']['mysqlService']['TestConnection'](arg1);
}

export function TransferData(arg1, arg2, arg3) {
  return window['go']['services']['mysqlService']['TransferData'](arg1, arg2, arg3);
}

export function Version(arg1) {
  return window['go']['services']['mysqlService']['Version'](arg1);
}
