// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {types} from '../models';

export function Startup(arg1:context.Context):Promise<void>;

export function TestConnection(arg1:types.MysqlConnection):Promise<types.JSResp>;
